# $Id: Makefile,v 1.1.1.1 2010/10/11 06:16:32 nelon Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

EXTRA_AFLAGS := -ansi
EXTRA_CFLAGS := -Werror

lib-y   := bootstr.o devops.o init.o misc.o \
	   tree.o console.o printf.o p1275.o cif.o
