# $Id: Makefile,v 1.1.1.1 2010/10/11 06:16:32 nelon Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
